#!/usr/bin/env ruby

#AUDIO="FA-66"
AUDIO="Laptop"

MIXER_CHANNELS=4

PORTS = {
  :mixer, 4243,
  :midi_osc, 4244
}

APPS = [
#  ["midi.osc", "./midi.osc -p #{PORTS[:midi_osc]}"],
#  ["jackminimix", "jackminimix -a -c #{MIXER_CHANNELS} -p #{PORTS[:mixer]}"]
#  ["jack.plumbing", "jack.plumbing -q"]
#  ["pianoteq", "./scripts/piano_runner"]
]

def start_studio
  APPS.each do |name, cmd|
    print "#{name}... "
    IO.popen("#{cmd} &")
    puts "done"
  end
end

def kill_studio
  `pkill -9 scsynth`
  APPS.each {|name, cmd| `pkill -9 #{name}`}
end

puts "\nInitializing studio..."

puts "Starting nailgun server..."
`pkill -9 java`
sleep 1
system("./scripts/ng-server &")

puts "Starting qjackctl..."
`pkill -9 jack`
sleep 1
system("qjackctl -s -p #{AUDIO} &")
sleep 1

puts "Starting pulseaudio in Jack mode..."
`pulseaudio -nF ~/.jack.pa --start`

kill_studio
start_studio
puts "\n...complete"

puts "\nAll systems go!\n\n"

if ARGV[0] == "-r"
  puts "Preparing to record session..."
  system("gtk-recordMyDesktop &")
end
