#!/bin/bash

DEPS=lib
SUBMODULES=src/lib

CLASSPATH=".:./src:./test:./src/lib:./session"

# Add jar files
for f in "$DEPS"/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

# Add sub-modules
for f in "$SUBMODULES"/**/src; do
    CLASSPATH=$CLASSPATH:$f
done

if [[ "$OSTYPE" == 'cygwin' ]]; then
  CLASSPATH=`cygpath -wp "$CLASSPATH"`
fi

echo "$CLASSPATH"
