#!/bin/bash

DEPS=lib

CLASSPATH=".:./src:./test:./src/extra:./session"

for f in "$DEPS"/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

if [[ "$OSTYPE" == 'cygwin' ]]; then
  CLASSPATH=`cygpath -wp "$CLASSPATH"`
fi

echo "$CLASSPATH"
