#!/bin/sh

# A simple script to start a repl with the project jar files (in the lib
# directory) on the classpath.

DEPS=deps

CLASSPATH=".:./src:./test:./src/extra:./session"

for f in "$DEPS"/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done
echo "Using classpath: $CLASSPATH"

if [[ "$OSTYPE" == 'cygwin' ]]; then
  CLASSPATH=`cygpath -wp "$CLASSPATH"`
fi

BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"

DEFINITIONS=-Djava.library.path=lib/opengl clojure.lang.Repl

# Ignore the opengl stuff for now...
rlwrap -a --remember -c -b "$BREAK_CHARS" -f "$HOME/.clj_completions" \
	  java -cp $CLASSPATH -Djava.library.path=lib/opengl clojure.lang.Repl
