#!/bin/bash

# A simple script to start a repl with the project jar files (in the lib
# directory) on the classpath.

SCRIPT_DIR=`dirname $0`
CLASSPATH=`$SCRIPT_DIR/java-cp`

#DEFINITIONS=-Djava.library.path=lib/opengl 

java -cp $CLASSPATH jline.ConsoleRunner clojure.main $@
