#!/bin/bash

WIN_ID=$(xwininfo | awk '/Window id:/ {print $4}')
REC=recordmydesktop --windowid $WIN_ID

SC=SuperCollider:out_1 SuperCollider:out_2
MIC="system:AC0_dev0_MicIn1 left"

TITLE=recorded-`date +%Y-%m-%d`.ogv

echo "Recording to file: $TITLE"
echo -n "Do you want to record from the Mic? ($MIC) [Y/n] [Enter]"
read mic

# Without Mic
#recordmydesktop --use-jack=SuperCollider:out_1,SuperCollider:out_2 -x 661 -y 56 --width=764 --height=827

# With Mic
$REC --use-jack $SC $MIC -o $TITLE
