#!/bin/sh 

# A simple script to start a repl with the project jar files (in the lib 
# directory) on the classpath.

CLASSPATH=".:./src"

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

# Need to figure out windows stuff again later...
#if [[ "$OSTYPE" == 'cygwin' ]]; then
#  CLASSPATH=`cygpath -wp "$CLASSPATH"`
#fi

BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"

echo "Using classpath: $CLASSPATH"

# Ignore the opengl stuff for now...
rlwrap -a --remember -c -b "$BREAK_CHARS" -f "$HOME/.clj_completions" \
	  java -cp $CLASSPATH -Djava.library.path=lib/opengl clojure.lang.Repl
